const app = require("quik-server")
const cors = require('cors')
const express = require("express")
const http = require('http')
const path = require("path")

// 
// webserver
// 
const webserverPort = 3000

app.use(cors())
app.quikAdd("quik-dom")
app.quikAdd("quik-backend")
app.use(express.static('./static_files'))

app.settings = {
    // default settings (all are optional)
    host: "localhost",
    port: webserverPort,
    // server can also be https (see: https://stackoverflow.com/questions/11744975/enabling-https-on-express-js)
    server: http.createServer(app),
    websiteFile: "./website.jsx",
    codeFolder: "./main",
    computerGeneratedFolder: "./autogenerated.ignore",
    bundlerOptions: {
        outDir: "./docs",
    }, // see https://parceljs.org/api.html for options
    afterServerStarted: () => {
        console.log(`Server running on http://localhost:${webserverPort}`)
    },
}
app.start()