import { Tutorializer, html } from "./autogenerated.ignore/bundle.js"

Tutorializer.intializeWholeWebpage()

// this file mainly exists for dev work and bundling 
// everything is in JS files so they can be imported over ES6
// Tutorializer.intializeWholeWebpage()